### ISSUE TITLE
Rotonde with broken index.html?

### ISSUE THREAD

**Issue by roxaloxa** [Rotonde/beaker#62] opened 2017-10-17 02:01 UTC
I just pulled latest and Rotonde doesn't load. Also `index.html` looks completely broken?

The changes made in https://github.com/Rotonde/beaker/commit/ea4224f33cde4a428877a96e542840bd6a462451 seem janked up.

**Comment by frozenpandaman** [comment] 2017-10-17 02:04
Recent commits (adding in Prettier) broke it for me as well.

Fixed by reverting to 7781521 (8dfd50e would've also been safe) for now. Had to manually back up and restore my `dat.json`, `portal.json`, and `links/custom.css`.

**Comment by neauoire** [comment] 2017-10-17 02:17
Oh my god, I'm so sorry. I was a bit too trusting, I merged @maxdeviant's PR without testing, it did indeed break everything for me as well. Reverted back to a working repo :) Sorry.

**Closed as completed by neauoire** 2017-10-17 02:17 UTC

**Comment by frozenpandaman** [comment] 2017-10-17 02:18
You're good! Thanks for the quick fix. 😊

**Comment by maxdeviant** [comment] 2017-10-17 02:22
@neauoire Does Beaker show errors in the console? Trying to debug what the issue is, but not seeing any errors.

**Comment by neauoire** [comment] 2017-10-17 02:23
No errors here, nothing shows up, it doesn't even seem to be parsing the index file has html.

**Comment by roxaloxa** [comment] 2017-10-17 02:25
What's the best way to rollback now? `git pull` is still saying I'm already up to date and I'm not the most git knowledgeable. 😅

**Comment by neauoire** [comment] 2017-10-17 02:28
Oh ho! did I break the tree for everyone!?
What a fiasco...

**Comment by maxdeviant** [comment] 2017-10-17 02:29
@neauoire There's a fixed PR in #63.
